### ISSUE TITLE
CTQ throw an error if you click on a red box

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#147] opened 2022-06-14 12:37 UTC
If you click on one of the red boxes in the "quick" part of CT (e.g. "lint" in this screenshot):

<img width="554" alt="screenshot_1696" src="https://user-images.githubusercontent.com/3046552/173578556-936d36a3-d522-4055-83ed-bcaf701bb77c.png">

... it throws an error to the console, and CT becomes unresponsive to input.  This does not happen with the non-quick red boxes.

@chrisklus related to yesterday's aqua changes?

```
aqua.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at My (aqua.min.js:1:1020511)
    at fire (aqua.min.js:1:1022525)
    at U.emit (aqua.min.js:1:15041)
    at Rh.emit (aqua.min.js:1:496908)
    at Ou.fire (aqua.min.js:1:647954)
    at aqua.min.js:1:648224
    at Ou.onRelease (aqua.min.js:1:643609)
    at qh.execute (aqua.min.js:1:500808)
    at Ou.release (aqua.min.js:1:641266)
    at Ou.release (aqua.min.js:1:648095)
```

**Comment by chrisklus** [comment] 2022-06-14 16:02
Thanks @pixelzoom. I removed a key that was apparently being accessed asynchronously as a global from another file. Seems like this code should be converted to TypeScript, that would have prevented this from happening (the irony!). I made a note in https://github.com/phetsims/aqua/issues/141.

For this issue, I pushed a fix, restarted CTQ, and the problem is no longer happening. Closing.

**Closed by chrisklus** 2022-06-14 16:02 UTC
Labels: type:bug, priority:2-high
