### ISSUE TITLE
Rosetta is missing from CTQ

### ISSUE THREAD

**Issue by liammulh** [phetsims/aqua#164] opened 2023-02-20 23:39 UTC
When I try to search for Rosetta on the CTQ page, this is what I see:

<img alt="no-rose" src="https://user-images.githubusercontent.com/60749003/219167004-169c1a87-e191-4897-ad2d-26aeeb20929e.png"/>

This might be related to https://github.com/phetsims/rosetta/issues/366. (I recently merged the development branch for Rosetta 2.0 into the master branch, and there have been a few problems getting it working with CT.) Assigning @zepumph because [this doc](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.json) says he is responsible dev.

@zepumph, if you would like help on this or if you'd like to pair, I am happy to help!

**Comment by zepumph** [comment] 2023-02-20 23:51
That filter is for CT in general, If you have tests for rosetta, you may be able to add those to listContinuousTests, but you said there was trouble. I'm not sure I understand what you have already tried, so I don't know what we want to add.

**Comment by liammulh** [comment] 2023-02-21 00:30
Sorry, I probably should have tried to provide more context.

CT and CTQ used to show the results of linting Rosetta (both before and after merging the development branch into the master branch). I have Rosetta configured to use PhET's ESLint configurations (both the sim and the Node versions). When I run `grunt lint` in Rosetta, it passes.

In https://github.com/phetsims/rosetta/issues/366, @samreid and I installed some missing dependencies in Rosetta, and that seemed to fix an error we were getting when we ran Perennial's `lint-everything` Grunt task.

So at some point, Rosetta seems to have disappeared from CTQ. I can't see Rosetta in CTQ right now:

<img width="778" alt="ctq" src="https://user-images.githubusercontent.com/60749003/220217536-ef3b3c2a-c719-4a79-b756-8b52019219e6.png">

**Comment by zepumph** [comment] 2023-02-21 17:51
I believe this is a duplicate of https://github.com/phetsims/rosetta/issues/366, please see my response in https://github.com/phetsims/rosetta/issues/366#issuecomment-1438878867.

I do want to note here though that CTQ (quick CT) is just the 5 green/red boxes at the top of the CT report. Everything else below (including the filtering) is normal CT testing. 

Feel free to close.

**Comment by zepumph** [comment] 2023-03-02 17:40
I'm going to close this, let me know if you want to discuss anything more.

**Closed by zepumph** 2023-03-02 17:41 UTC
